// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OGPositionCommon.proto

package com.ourgame.mahjong.message.chat;

public final class OGPositionCommon {
  private OGPositionCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.ourgame.mahjong.message.chat.E_Pos_CoinType}
   */
  public enum E_Pos_CoinType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CT_UNDEFINED = 0;</code>
     *
     * <pre>
     * 未定义
     * </pre>
     */
    CT_UNDEFINED(0, 0),
    /**
     * <code>CT_INTEGRAL = 1;</code>
     *
     * <pre>
     * 积分
     * </pre>
     */
    CT_INTEGRAL(1, 1),
    /**
     * <code>CT_GOLD = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    CT_GOLD(2, 2),
    /**
     * <code>CT_WND = 3;</code>
     *
     * <pre>
     * 万能豆
     * </pre>
     */
    CT_WND(3, 3),
    ;

    /**
     * <code>CT_UNDEFINED = 0;</code>
     *
     * <pre>
     * 未定义
     * </pre>
     */
    public static final int CT_UNDEFINED_VALUE = 0;
    /**
     * <code>CT_INTEGRAL = 1;</code>
     *
     * <pre>
     * 积分
     * </pre>
     */
    public static final int CT_INTEGRAL_VALUE = 1;
    /**
     * <code>CT_GOLD = 2;</code>
     *
     * <pre>
     * 金币
     * </pre>
     */
    public static final int CT_GOLD_VALUE = 2;
    /**
     * <code>CT_WND = 3;</code>
     *
     * <pre>
     * 万能豆
     * </pre>
     */
    public static final int CT_WND_VALUE = 3;


    public final int getNumber() { return value; }

    public static E_Pos_CoinType valueOf(int value) {
      switch (value) {
        case 0: return CT_UNDEFINED;
        case 1: return CT_INTEGRAL;
        case 2: return CT_GOLD;
        case 3: return CT_WND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<E_Pos_CoinType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<E_Pos_CoinType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<E_Pos_CoinType>() {
            public E_Pos_CoinType findValueByNumber(int number) {
              return E_Pos_CoinType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ourgame.mahjong.message.chat.OGPositionCommon.getDescriptor().getEnumTypes().get(0);
    }

    private static final E_Pos_CoinType[] VALUES = values();

    public static E_Pos_CoinType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private E_Pos_CoinType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ourgame.mahjong.message.chat.E_Pos_CoinType)
  }

  public interface Pos_PositionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];
    /**
     * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
     */
    boolean hasCoinType();
    /**
     * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
     */
    com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType getCoinType();

    // optional int32 ChannelID = 2 [default = -1];
    /**
     * <code>optional int32 ChannelID = 2 [default = -1];</code>
     *
     * <pre>
     * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
     * </pre>
     */
    boolean hasChannelID();
    /**
     * <code>optional int32 ChannelID = 2 [default = -1];</code>
     *
     * <pre>
     * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
     * </pre>
     */
    int getChannelID();

    // optional int32 GameID = 3 [default = 0];
    /**
     * <code>optional int32 GameID = 3 [default = 0];</code>
     */
    boolean hasGameID();
    /**
     * <code>optional int32 GameID = 3 [default = 0];</code>
     */
    int getGameID();

    // optional int32 GroupID = 4 [default = 0];
    /**
     * <code>optional int32 GroupID = 4 [default = 0];</code>
     */
    boolean hasGroupID();
    /**
     * <code>optional int32 GroupID = 4 [default = 0];</code>
     */
    int getGroupID();

    // optional int64 RoomID = 5 [default = 0];
    /**
     * <code>optional int64 RoomID = 5 [default = 0];</code>
     */
    boolean hasRoomID();
    /**
     * <code>optional int64 RoomID = 5 [default = 0];</code>
     */
    long getRoomID();
  }
  /**
   * Protobuf type {@code com.ourgame.mahjong.message.chat.Pos_Position}
   */
  public static final class Pos_Position extends
      com.google.protobuf.GeneratedMessage
      implements Pos_PositionOrBuilder {
    // Use Pos_Position.newBuilder() to construct.
    private Pos_Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pos_Position(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pos_Position defaultInstance;
    public static Pos_Position getDefaultInstance() {
      return defaultInstance;
    }

    public Pos_Position getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pos_Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType value = com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                coinType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channelID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gameID_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              groupID_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              roomID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ourgame.mahjong.message.chat.OGPositionCommon.internal_static_com_ourgame_mahjong_message_chat_Pos_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ourgame.mahjong.message.chat.OGPositionCommon.internal_static_com_ourgame_mahjong_message_chat_Pos_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.class, com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.Builder.class);
    }

    public static com.google.protobuf.Parser<Pos_Position> PARSER =
        new com.google.protobuf.AbstractParser<Pos_Position>() {
      public Pos_Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pos_Position(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pos_Position> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];
    public static final int COINTYPE_FIELD_NUMBER = 1;
    private com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType coinType_;
    /**
     * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
     */
    public boolean hasCoinType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
     */
    public com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType getCoinType() {
      return coinType_;
    }

    // optional int32 ChannelID = 2 [default = -1];
    public static final int CHANNELID_FIELD_NUMBER = 2;
    private int channelID_;
    /**
     * <code>optional int32 ChannelID = 2 [default = -1];</code>
     *
     * <pre>
     * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
     * </pre>
     */
    public boolean hasChannelID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 ChannelID = 2 [default = -1];</code>
     *
     * <pre>
     * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
     * </pre>
     */
    public int getChannelID() {
      return channelID_;
    }

    // optional int32 GameID = 3 [default = 0];
    public static final int GAMEID_FIELD_NUMBER = 3;
    private int gameID_;
    /**
     * <code>optional int32 GameID = 3 [default = 0];</code>
     */
    public boolean hasGameID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 GameID = 3 [default = 0];</code>
     */
    public int getGameID() {
      return gameID_;
    }

    // optional int32 GroupID = 4 [default = 0];
    public static final int GROUPID_FIELD_NUMBER = 4;
    private int groupID_;
    /**
     * <code>optional int32 GroupID = 4 [default = 0];</code>
     */
    public boolean hasGroupID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 GroupID = 4 [default = 0];</code>
     */
    public int getGroupID() {
      return groupID_;
    }

    // optional int64 RoomID = 5 [default = 0];
    public static final int ROOMID_FIELD_NUMBER = 5;
    private long roomID_;
    /**
     * <code>optional int64 RoomID = 5 [default = 0];</code>
     */
    public boolean hasRoomID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 RoomID = 5 [default = 0];</code>
     */
    public long getRoomID() {
      return roomID_;
    }

    private void initFields() {
      coinType_ = com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType.CT_UNDEFINED;
      channelID_ = -1;
      gameID_ = 0;
      groupID_ = 0;
      roomID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, coinType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, channelID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gameID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, groupID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, roomID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, coinType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channelID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gameID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, groupID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, roomID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ourgame.mahjong.message.chat.Pos_Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ourgame.mahjong.message.chat.OGPositionCommon.internal_static_com_ourgame_mahjong_message_chat_Pos_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ourgame.mahjong.message.chat.OGPositionCommon.internal_static_com_ourgame_mahjong_message_chat_Pos_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.class, com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.Builder.class);
      }

      // Construct using com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        coinType_ = com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType.CT_UNDEFINED;
        bitField0_ = (bitField0_ & ~0x00000001);
        channelID_ = -1;
        bitField0_ = (bitField0_ & ~0x00000002);
        gameID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        groupID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        roomID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ourgame.mahjong.message.chat.OGPositionCommon.internal_static_com_ourgame_mahjong_message_chat_Pos_Position_descriptor;
      }

      public com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position getDefaultInstanceForType() {
        return com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.getDefaultInstance();
      }

      public com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position build() {
        com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position buildPartial() {
        com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position result = new com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.coinType_ = coinType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channelID_ = channelID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gameID_ = gameID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.groupID_ = groupID_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.roomID_ = roomID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position) {
          return mergeFrom((com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position other) {
        if (other == com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position.getDefaultInstance()) return this;
        if (other.hasCoinType()) {
          setCoinType(other.getCoinType());
        }
        if (other.hasChannelID()) {
          setChannelID(other.getChannelID());
        }
        if (other.hasGameID()) {
          setGameID(other.getGameID());
        }
        if (other.hasGroupID()) {
          setGroupID(other.getGroupID());
        }
        if (other.hasRoomID()) {
          setRoomID(other.getRoomID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ourgame.mahjong.message.chat.OGPositionCommon.Pos_Position) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];
      private com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType coinType_ = com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType.CT_UNDEFINED;
      /**
       * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
       */
      public boolean hasCoinType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
       */
      public com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType getCoinType() {
        return coinType_;
      }
      /**
       * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
       */
      public Builder setCoinType(com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        coinType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.ourgame.mahjong.message.chat.E_Pos_CoinType CoinType = 1 [default = CT_UNDEFINED];</code>
       */
      public Builder clearCoinType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        coinType_ = com.ourgame.mahjong.message.chat.OGPositionCommon.E_Pos_CoinType.CT_UNDEFINED;
        onChanged();
        return this;
      }

      // optional int32 ChannelID = 2 [default = -1];
      private int channelID_ = -1;
      /**
       * <code>optional int32 ChannelID = 2 [default = -1];</code>
       *
       * <pre>
       * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
       * </pre>
       */
      public boolean hasChannelID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 ChannelID = 2 [default = -1];</code>
       *
       * <pre>
       * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
       * </pre>
       */
      public int getChannelID() {
        return channelID_;
      }
      /**
       * <code>optional int32 ChannelID = 2 [default = -1];</code>
       *
       * <pre>
       * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
       * </pre>
       */
      public Builder setChannelID(int value) {
        bitField0_ |= 0x00000002;
        channelID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ChannelID = 2 [default = -1];</code>
       *
       * <pre>
       * -1: 所有渠道，-2: 所有混服，其它值: 某特定渠道
       * </pre>
       */
      public Builder clearChannelID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channelID_ = -1;
        onChanged();
        return this;
      }

      // optional int32 GameID = 3 [default = 0];
      private int gameID_ ;
      /**
       * <code>optional int32 GameID = 3 [default = 0];</code>
       */
      public boolean hasGameID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 GameID = 3 [default = 0];</code>
       */
      public int getGameID() {
        return gameID_;
      }
      /**
       * <code>optional int32 GameID = 3 [default = 0];</code>
       */
      public Builder setGameID(int value) {
        bitField0_ |= 0x00000004;
        gameID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 GameID = 3 [default = 0];</code>
       */
      public Builder clearGameID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gameID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 GroupID = 4 [default = 0];
      private int groupID_ ;
      /**
       * <code>optional int32 GroupID = 4 [default = 0];</code>
       */
      public boolean hasGroupID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 GroupID = 4 [default = 0];</code>
       */
      public int getGroupID() {
        return groupID_;
      }
      /**
       * <code>optional int32 GroupID = 4 [default = 0];</code>
       */
      public Builder setGroupID(int value) {
        bitField0_ |= 0x00000008;
        groupID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 GroupID = 4 [default = 0];</code>
       */
      public Builder clearGroupID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupID_ = 0;
        onChanged();
        return this;
      }

      // optional int64 RoomID = 5 [default = 0];
      private long roomID_ ;
      /**
       * <code>optional int64 RoomID = 5 [default = 0];</code>
       */
      public boolean hasRoomID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 RoomID = 5 [default = 0];</code>
       */
      public long getRoomID() {
        return roomID_;
      }
      /**
       * <code>optional int64 RoomID = 5 [default = 0];</code>
       */
      public Builder setRoomID(long value) {
        bitField0_ |= 0x00000010;
        roomID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 RoomID = 5 [default = 0];</code>
       */
      public Builder clearRoomID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roomID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ourgame.mahjong.message.chat.Pos_Position)
    }

    static {
      defaultInstance = new Pos_Position(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ourgame.mahjong.message.chat.Pos_Position)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ourgame_mahjong_message_chat_Pos_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ourgame_mahjong_message_chat_Pos_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026OGPositionCommon.proto\022 com.ourgame.ma" +
      "hjong.message.chat\"\261\001\n\014Pos_Position\022P\n\010C" +
      "oinType\030\001 \001(\01620.com.ourgame.mahjong.mess" +
      "age.chat.E_Pos_CoinType:\014CT_UNDEFINED\022\025\n" +
      "\tChannelID\030\002 \001(\005:\002-1\022\021\n\006GameID\030\003 \001(\005:\0010\022" +
      "\022\n\007GroupID\030\004 \001(\005:\0010\022\021\n\006RoomID\030\005 \001(\003:\0010*L" +
      "\n\016E_Pos_CoinType\022\020\n\014CT_UNDEFINED\020\000\022\017\n\013CT" +
      "_INTEGRAL\020\001\022\013\n\007CT_GOLD\020\002\022\n\n\006CT_WND\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ourgame_mahjong_message_chat_Pos_Position_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ourgame_mahjong_message_chat_Pos_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ourgame_mahjong_message_chat_Pos_Position_descriptor,
              new java.lang.String[] { "CoinType", "ChannelID", "GameID", "GroupID", "RoomID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
